### ISSUE TITLE
Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by derdawid** [smartapps-fr/bitbucket-pipelines-php-mysql#1]
Recently my builds are not working with the following result. It was working previously. 

mysql -h localhost -u root -e "CREATE DATABASE symfony;"
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

bitbucket-pipelines.yml
`image: smartapps/bitbucket-pipelines-php-mysql

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt-get -y update
          - apt-get -y install php5-sqlite
          - service mysql start
          - mysql -h localhost -u root -e "CREATE DATABASE symfony;"
          - php5dismod -s cli xdebug
          - composer --version
          - cp app/config/parameters.yml.dist app/config/parameters.yml
          - composer install
          - php bin/console doctrine:database:create --env=test
          - php phpunit.phar `

**Comment by ddebin** [comment]
Sorry, as said in the last commit, MySQL user root has a password `root` now, instead of blank. You should replace `mysql -h localhost -u root -e "CREATE DATABASE symfony;"` by `mysql -h localhost -u root -proot -e "CREATE DATABASE symfony;"`.

**Comment by derdawid** [comment]
Works fine, thx for this and updating the docs.

**Comment by ddebin** [comment]
I added a `0.1` docker image tag with old behavior (blank root password for MySQL) if you need it.
