### ISSUE TITLE
Increasing Xdebug's max_nesting_level

### ISSUE THREAD

**Issue by FlorianKromer** [smartapps-fr/bitbucket-pipelines-php-mysql#12]
I got the famous error: "Maximum function nesting level of '100' reached" by testing my symfony project. I know sometime it could be interesting to detect a big function nesting... but 100 is a bit low in our days.

What about change the xdebug.max_nesting_level to 200 in the php.ini file?

Thank you for your work :smile: .

**Comment by ddebin** [comment]
OK. Updated main/stretch branch (1332ea7).
