### ISSUE TITLE
PHPunit on php 5.6.30

### ISSUE THREAD

**Issue by FlorianKromer** [smartapps-fr/bitbucket-pipelines-php-mysql#13]
Hello!
I got this error on the master branch:

> This version of PHPUnit is supported on PHP 7.0 and PHP 7.1.
> You are using PHP 5.6.30-0+deb8u1 (/usr/bin/php5).

I think the problem is the main branch is based on php 5.6.30 but the latest PHPunit version works only on PHP 7.0

The version phpunit 5.7 should works: https://phar.phpunit.de/phpunit-5.7.phar .

**Comment by ddebin** [comment]
Thanks. Solved with commit a448388.
