### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by drupov** [smartapps-fr/bitbucket-pipelines-php-mysql#15]
Hi,

is there a possibility to have a branch for PHP 7.1 too?

**Comment by paulocastellano** [comment]
+1

**Comment by rvanlaak** [comment]
The `stretch` branch could get upgraded to `7.1`, as there aren't any BC breaks.

**Comment by ddebin** [comment]
[A new repo](https://github.com/smartapps-fr/bitbucket-pipelines-debian-9) has been created (based on this branch - `stretch`) with PHP 7.0/7.1 and Node 6 (with `n` to manage _node.js_ versions).
