### ISSUE TITLE
Up-to-date applications

### ISSUE THREAD

**Issue by bertalanimre** [smartapps-fr/bitbucket-pipelines-php-mysql#16]
Hey There!

Not really an issue, but can you modify the docker to use the following?
- PHP 7.1
- NodeJS 6.11
- MySQL 5.7

The packages you are using are very old and most of them are not used by any correct webdeveloping company.

**Comment by ddebin** [comment]
[A new repo](https://github.com/smartapps-fr/bitbucket-pipelines-debian-9) has been created (based on `Stretch` branch) with PHP 7.0/7.1 and Node 6 (with `n` to manage _node.js_ versions).
