### ISSUE TITLE
Utf8mb4 collation support

### ISSUE THREAD

**Issue by MBoretto** [smartapps-fr/bitbucket-pipelines-php-mysql#6]
Hello!
I would like to test your container but I found out that pdo driver is not installed. I possible to add it? 
Thanks 
Marco

**Comment by ddebin** [comment]
`php5-mysqlnd` Debian package already includes `pdo_mysql` PHP module. Do you need something else ?

**Comment by MBoretto** [comment]
Sorry didn't know this. Is possible to have a version of mysql greater than 5.5 in order to support  utf8mb4 collation? thanks

**Comment by ddebin** [comment]
This image is based on Debian _stable_ (_Jessie_ as of 11/2016), MySQL server included is `5.5`. But MySQL 5.5 fully support utf8mb4 collation, I use it myself.

**Comment by MBoretto** [comment]
I got this error:
```
PDOException: SQLSTATE[HY000]: General error: 1273 Unknown collation: 'utf8mb4_unicode_520_ci'
```
Maybe collation 520 is not supported in this version?
Has Debian switched from MySQL to MariaDB?

**Comment by ddebin** [comment]
`SHOW COLLATION;`show all collations, `utf8mb4_unicode_520_ci ` is not available, I personally use `utf8mb4_unicode_ci `. Debian _Jessie_ has both MySQL 5.5 and MariaDB 10.0.

**Comment by ddebin** [comment]
If you are interested, I can start a branch with Debian _Stretch_ (_Testing_), PHP 7 and MySQL 5.6.

**Comment by MBoretto** [comment]
Thanks but I built my own one that reflect the production environment (alpine 3.4): https://hub.docker.com/r/mboretto/bitbucket-pipelines-php-mysql/

Someone has already fork your repo  to let it work with mysql5.6
Thanks for the hints!
