### ISSUE TITLE
mbstring extension missing

### ISSUE THREAD

**Issue by mrgrain** [smartapps-fr/bitbucket-pipelines-php-mysql#7]
Hey, what about adding mbstring to the container? Seems fairly common to me, e.g. it is a requirement for Laravel: https://laravel.com/docs/5.3/installation#server-requirements

**Comment by ddebin** [comment]
Extension is already included in `php5-cli` cf. https://packages.debian.org/jessie/php5-cli.

**Comment by ddebin** [comment]
Extension `php7.0-mbstring` has been added to `stretch` (php7.0) branch.
